version: '3.3'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile
    container_name: derrick-app
    restart: always
    working_dir: /var/www
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: derrick-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: derrick-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: derrick-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
